export const COPY = {
  fa: {
    metaTitle: "نمونه‌کار",
    metaDesc:
      "پوستر، ویدیو و کپشن واقعی تولیدشده با آپ‌مارکت — برای پوشاک، اکسسوری و دکوراسیون.",
    eyebrow: "نمونه‌کار",
    title: "خروجی واقعی، نه نمونه‌ی تبلیغاتی",
    lead: "این‌ها با همان سیستمی ساخته شده‌اند که شما استفاده می‌کنید.",
    empty: "نمونه‌کارها در حال آماده‌سازی‌اند.",
    posterAlt: (p: string) => `پوستر تبلیغاتی تولیدشده با آپ‌مارکت برای ${p}`,
    segmentAlt: (n: string, p: string) => `قطعه ${n} از ویدیوی ${p}`,
    captionLabel: "کپشن تولیدشده",
    howEyebrow: "چطور ساخته شدند",
    howTitle: "همان مسیری که برای شما طی می‌شود",
    steps: [
      { icon: "📷", t: "عکس محصول", d: "ورودی: یک عکس واقعی، بدون استودیو" },
      { icon: "🧠", t: "تحلیل", d: "مدل بینایی عکس را می‌خواند، مدل استدلال استراتژی می‌سازد" },
      { icon: "🎨", t: "تولید", d: "پوستر، ویدیو و کپشن از همان یک ورودی" },
      { icon: "✅", t: "تأیید", d: "شما می‌بینید و تصمیم می‌گیرید" },
    ],
    ctaTitle: "نمونه‌ی محصول خودتان را بگیرید",
    ctaLead:
      "فروشگاهتان را ثبت کنید و در همین جلسه ببینید خروجی برای محصول خودتان چه شکلی است.",
    seePricing: "دیدن قیمت‌ها",
  },
  en: {
    metaTitle: "Showcase",
    metaDesc:
      "Real posters, video and captions produced by UpMarket — for clothing, accessories and home decor.",
    eyebrow: "Showcase",
    title: "Real output, not a marketing mock-up",
    lead: "These were made with the same system you would be using.",
    empty: "Samples are being prepared.",
    posterAlt: (p: string) => `An advertising poster generated by UpMarket for ${p}`,
    segmentAlt: (n: string, p: string) => `Segment ${n} of the ${p} video`,
    captionLabel: "Generated caption",
    howEyebrow: "How they were made",
    howTitle: "The same path yours would take",
    steps: [
      { icon: "📷", t: "Product photo", d: "Input: one real photo, no studio" },
      { icon: "🧠", t: "Analysis", d: "A vision model reads the photo, a reasoning model builds the strategy" },
      { icon: "🎨", t: "Generation", d: "Poster, video and caption from that one input" },
      { icon: "✅", t: "Approval", d: "You look at it and decide" },
    ],
    ctaTitle: "Get a sample of your own product",
    ctaLead:
      "Add your shop and see, in this sitting, what the output looks like for your own product.",
    seePricing: "See pricing",
  },
} as const;
