# Generated by Django 5.2.10 on 2026-09-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("business", models.CharField(blank=True, max_length=160)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("DEMO", "درخواست دمو"),
                            ("PRICING", "سؤال درباره قیمت"),
                            ("SUPPORT", "پشتیبانی"),
                            ("PARTNERSHIP", "همکاری"),
                            ("OTHER", "موضوع دیگر"),
                        ],
                        default="OTHER",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "جدید"),
                            ("CONTACTED", "تماس گرفته شد"),
                            ("QUALIFIED", "واجد شرایط"),
                            ("CONVERTED", "تبدیل به مشتری"),
                            ("SPAM", "اسپم"),
                            ("CLOSED", "بسته\u200cشده"),
                        ],
                        default="NEW",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("source_path", models.CharField(blank=True, max_length=300)),
                ("referrer", models.CharField(blank=True, max_length=300)),
                ("utm", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name": "لید",
                "verbose_name_plural": "لیدها",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="marketing_l_status_6fbd54_idx",
                    ),
                    models.Index(fields=["email"], name="marketing_l_email_c4b755_idx"),
                ],
            },
        ),
    ]
