# Generated by Django 5.2.10 on 2026-09-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("page_view", "بازدید صفحه"),
                            ("cta_click", "کلیک روی دکمه"),
                            ("pricing_view", "دیدن قیمت\u200cها"),
                            ("plan_selected", "انتخاب پلن"),
                            ("contact_submitted", "ارسال فرم تماس"),
                            ("signup_started", "شروع ثبت\u200cنام"),
                            ("signup_completed", "تکمیل ثبت\u200cنام"),
                            ("tool_used", "استفاده از ابزار رایگان"),
                        ],
                        max_length=24,
                    ),
                ),
                ("session", models.CharField(db_index=True, max_length=40)),
                ("path", models.CharField(blank=True, max_length=300)),
                ("locale", models.CharField(blank=True, max_length=5)),
                ("referrer", models.CharField(blank=True, max_length=300)),
                ("utm", models.JSONField(blank=True, default=dict)),
                ("props", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "رویداد",
                "verbose_name_plural": "رویدادها",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["name", "-created_at"],
                        name="marketing_e_name_edb8ab_idx",
                    ),
                    models.Index(
                        fields=["session", "created_at"],
                        name="marketing_e_session_f9a476_idx",
                    ),
                ],
            },
        ),
    ]
