# Generated by Django 5.2.10 on 2026-09-09 08:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0004_alter_job_type"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("price_toman", models.PositiveIntegerField(default=0)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="در صفحه\u200cی قیمت\u200cگذاری سایت نمایش داده شود",
                    ),
                ),
                (
                    "is_trial",
                    models.BooleanField(
                        default=False, help_text="پلن آزمایشی — با محدودیت زمانی"
                    ),
                ),
                ("trial_days", models.PositiveSmallIntegerField(default=0)),
                ("sort_order", models.PositiveSmallIntegerField(default=100)),
                (
                    "video_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="مجموع ثانیه ویدیو در هر دوره"
                    ),
                ),
                (
                    "images",
                    models.PositiveIntegerField(
                        default=0, help_text="تصویر در هر دوره"
                    ),
                ),
                (
                    "captions",
                    models.PositiveIntegerField(default=0, help_text="کپشن در هر دوره"),
                ),
                (
                    "max_products",
                    models.PositiveIntegerField(default=0, help_text="۰ = نامحدود"),
                ),
                ("max_stores", models.PositiveSmallIntegerField(default=1)),
                ("allows_publishing", models.BooleanField(default=True)),
                ("allows_sales_agent", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "price_toman"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIALING", "دوره آزمایشی"),
                            ("ACTIVE", "فعال"),
                            ("PAST_DUE", "پرداخت\u200cنشده"),
                            ("CANCELLED", "لغو\u200cشده"),
                            ("EXPIRED", "منقضی"),
                        ],
                        default="TRIALING",
                        max_length=10,
                    ),
                ),
                (
                    "period_start",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("period_end", models.DateTimeField()),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("bonus_video_seconds", models.PositiveIntegerField(default=0)),
                ("bonus_images", models.PositiveIntegerField(default=0)),
                ("bonus_captions", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                    ),
                ),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("VIDEO_SECONDS", "ثانیه ویدیو"),
                            ("IMAGES", "تصویر"),
                            ("CAPTIONS", "کپشن"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RESERVED", "رزرو\u200cشده"),
                            ("COMMITTED", "مصرف\u200cشده"),
                            ("RELEASED", "آزاد\u200cشده"),
                        ],
                        default="RESERVED",
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("detail", models.CharField(blank=True, max_length=120)),
                ("external", models.BooleanField(default=False)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage",
                        to="jobs.job",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage",
                        to="stores.store",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subscription", "metric", "period_start", "state"],
                        name="billing_usa_subscri_451d6a_idx",
                    ),
                    models.Index(
                        fields=["store", "created_at"],
                        name="billing_usa_store_i_5eb71e_idx",
                    ),
                ],
            },
        ),
    ]
