# Generated by Django 5.2.10 on 2026-09-12 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("stores", "0002_storeprofile_novinhub_account_ids_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_toman", models.PositiveIntegerField()),
                ("provider", models.CharField(max_length=24)),
                ("token", models.CharField(blank=True, db_index=True, max_length=120)),
                ("reference", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار پرداخت"),
                            ("PAID", "پرداخت\u200cشده"),
                            ("FAILED", "ناموفق"),
                            ("ABANDONED", "رها\u200cشده"),
                            ("REFUNDED", "بازگردانده\u200cشده"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=24, unique=True),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("refund_reason", models.CharField(blank=True, max_length=300)),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("error", models.CharField(blank=True, max_length=300)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billing.plan",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="stores.store",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BillingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SUB_CREATED", "ایجاد اشتراک"),
                            ("PLAN_CHANGED", "تغییر پلن"),
                            ("PAY_STARTED", "شروع پرداخت"),
                            ("PAY_PAID", "پرداخت موفق"),
                            ("PAY_FAILED", "پرداخت ناموفق"),
                            ("PAY_REFUNDED", "بازگشت وجه"),
                            ("ACTIVATED", "فعال\u200cسازی"),
                            ("RENEWED", "تمدید"),
                            ("CANCELLED", "لغو"),
                            ("EXPIRED", "انقضا"),
                            ("GRACE", "شروع مهلت ارفاقی"),
                        ],
                        max_length=16,
                    ),
                ),
                ("summary", models.CharField(max_length=300)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_events",
                        to="stores.store",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="billing.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد صورتحساب",
                "verbose_name_plural": "رویدادهای صورتحساب",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["store", "-created_at"], name="billing_pay_store_i_67b1c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "-created_at"], name="billing_pay_status_bc3ae3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingevent",
            index=models.Index(
                fields=["store", "-created_at"], name="billing_bil_store_i_7329be_idx"
            ),
        ),
    ]
