# Generated by Django 5.2.10 on 2026-09-12 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_payment_billingevent_and_more"),
        ("jobs", "0004_alter_job_type"),
        ("stores", "0002_storeprofile_novinhub_account_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usage",
            name="attempt",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="usage",
            name="quality_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="usage",
            name="quality_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CUSTOMER", "نظر فروشگاه\u200cدار"),
                    ("AUTO", "بررسی خودکار"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="usage",
            name="retry_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retries",
                to="billing.usage",
            ),
        ),
        migrations.AlterField(
            model_name="billingevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SUB_CREATED", "ایجاد اشتراک"),
                    ("PLAN_CHANGED", "تغییر پلن"),
                    ("PAY_STARTED", "شروع پرداخت"),
                    ("PAY_PAID", "پرداخت موفق"),
                    ("PAY_FAILED", "پرداخت ناموفق"),
                    ("PAY_REFUNDED", "بازگشت وجه"),
                    ("ACTIVATED", "فعال\u200cسازی"),
                    ("RENEWED", "تمدید"),
                    ("CANCELLED", "لغو"),
                    ("EXPIRED", "انقضا"),
                    ("GRACE", "شروع مهلت ارفاقی"),
                    ("CREDIT_BACK", "برگشت اعتبار (کیفیت)"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="usage",
            name="state",
            field=models.CharField(
                choices=[
                    ("RESERVED", "رزرو\u200cشده"),
                    ("COMMITTED", "مصرف\u200cشده"),
                    ("RELEASED", "آزاد\u200cشده"),
                    ("REFUNDED", "برگشت\u200cخورده (کیفیت)"),
                ],
                default="RESERVED",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="usage",
            index=models.Index(
                fields=["job", "state"], name="billing_usa_job_id_00064c_idx"
            ),
        ),
    ]
