# Generated by Django 5.2.10 on 2026-08-27 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=220, unique=True
                    ),
                ),
                ("business_type", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("target_audience", models.CharField(blank=True, max_length=255)),
                ("contact", models.JSONField(blank=True, default=dict)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="stores/logos/"),
                ),
                ("colors", models.JSONField(blank=True, default=dict)),
                ("social_links", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_voice", models.CharField(blank=True, max_length=100)),
                ("tone", models.CharField(blank=True, max_length=100)),
                ("content_style", models.CharField(blank=True, max_length=100)),
                ("visual_preferences", models.JSONField(blank=True, default=dict)),
                ("shipping_policy", models.TextField(blank=True)),
                ("return_policy", models.TextField(blank=True)),
                ("refund_policy", models.TextField(blank=True)),
                ("payment_info", models.TextField(blank=True)),
                ("business_rules", models.TextField(blank=True)),
                ("working_hours", models.JSONField(blank=True, default=dict)),
                ("ai_preferences", models.JSONField(blank=True, default=dict)),
                ("publishing_preferences", models.JSONField(blank=True, default=dict)),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="stores.store",
                    ),
                ),
            ],
        ),
    ]
