# Generated by Django 5.2.10 on 2026-09-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeprofile",
            name="novinhub_account_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="شناسه\u200cی اکانت\u200cهای اینستاگرام که پست روی آن\u200cها منتشر می\u200cشود",
            ),
        ),
        migrations.AddField(
            model_name="storeprofile",
            name="novinhub_token",
            field=models.CharField(
                blank=True,
                help_text="توکن اختصاصی نوین\u200cهاب این فروشگاه (اختیاری)",
                max_length=255,
            ),
        ),
    ]
