# Generated by Django 5.2.10 on 2026-09-12 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_storeprofile_novinhub_account_ids_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "مالک"),
                            ("ADMIN", "مدیر"),
                            ("MARKETING", "بازاریابی"),
                            ("CONTENT", "مدیر محتوا"),
                            ("SUPPORT", "پشتیبانی"),
                            ("VIEWER", "بازدیدکننده"),
                        ],
                        default="VIEWER",
                        max_length=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="stores.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "عضو فروشگاه",
                "verbose_name_plural": "اعضای فروشگاه",
                "ordering": ["store", "role", "id"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="stores_memb_user_id_0ad249_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "user"), name="one_seat_per_user_per_store"
                    )
                ],
            },
        ),
    ]
