# Generated by Django 5.2.10 on 2026-09-12 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0003_membership"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesAgentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("FORMAL", "رسمی"),
                            ("FRIENDLY", "دوستانه"),
                            ("PROFESSIONAL", "حرفه\u200cای"),
                            ("WARM", "صمیمی"),
                            ("CUSTOM", "لحن سفارشی خودم"),
                        ],
                        default="FRIENDLY",
                        max_length=14,
                    ),
                ),
                (
                    "custom_tone",
                    models.TextField(
                        blank=True,
                        help_text="اگر «لحن سفارشی» را انتخاب کردی، اینجا توضیح بده چطور حرف بزند.",
                        verbose_name="لحن سفارشی",
                    ),
                ),
                (
                    "always_say",
                    models.TextField(
                        blank=True,
                        help_text="مثلاً: «ارسال تهران همان\u200cروز است» یا «ضمانت اصالت کالا داریم».",
                        verbose_name="همیشه این\u200cها را بگو",
                    ),
                ),
                (
                    "never_say",
                    models.TextField(
                        blank=True,
                        help_text="هر خط یک عبارت. اگر جواب مدل شامل این عبارت\u200cها باشد، جواب رد می\u200cشود و دوباره تولید می\u200cشود.",
                        verbose_name="هرگز این\u200cها را نگو",
                    ),
                ),
                (
                    "sale_terms",
                    models.TextField(
                        blank=True,
                        help_text="حداقل سفارش، شهرهای تحت پوشش، شرایط پیش\u200cپرداخت…",
                        verbose_name="شرایط فروش",
                    ),
                ),
                (
                    "limits",
                    models.TextField(
                        blank=True,
                        help_text="کارهایی که ایجنت نباید انجام دهد — مثلاً قول زمان دقیق تحویل ندهد.",
                        verbose_name="محدودیت\u200cها",
                    ),
                ),
                (
                    "can_offer_discount",
                    models.BooleanField(
                        default=False,
                        help_text="خاموش یعنی ایجنت هیچ تخفیفی پیشنهاد نمی\u200cدهد و سؤال تخفیف را به شما ارجاع می\u200cدهد.",
                        verbose_name="اجازه\u200cی پیشنهاد تخفیف",
                    ),
                ),
                (
                    "discount_policy",
                    models.TextField(
                        blank=True,
                        help_text="کِی و چقدر. مثلاً «بالای ۳ عدد، ۱۰٪».",
                        verbose_name="سیاست تخفیف",
                    ),
                ),
                (
                    "escalate_on_complaint",
                    models.BooleanField(
                        default=True,
                        help_text="مشتری ناراضی معمولاً جواب انسان می\u200cخواهد، نه جواب درست.",
                        verbose_name="شکایت را به آدم ارجاع بده",
                    ),
                ),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_settings",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات ایجنت فروش",
                "verbose_name_plural": "تنظیمات ایجنت فروش",
            },
        ),
    ]
