# Generated by Django 5.2.10 on 2026-08-27 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0003_marketresearch"),
        ("products", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Caption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("INSTAGRAM", "Instagram"),
                            ("TELEGRAM", "Telegram"),
                            ("LINKEDIN", "LinkedIn"),
                        ],
                        max_length=16,
                    ),
                ),
                ("tone", models.CharField(blank=True, max_length=100)),
                ("objective", models.CharField(blank=True, max_length=200)),
                ("short_text", models.TextField(blank=True)),
                ("medium_text", models.TextField(blank=True)),
                ("long_text", models.TextField(blank=True)),
                ("hashtags", models.JSONField(blank=True, default=list)),
                ("cta", models.CharField(blank=True, max_length=300)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captions",
                        to="products.product",
                    ),
                ),
                (
                    "source_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ai.airequest",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captions",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("concept", models.TextField(blank=True)),
                ("objective", models.CharField(blank=True, max_length=200)),
                ("cta", models.CharField(blank=True, max_length=300)),
                ("total_duration", models.PositiveIntegerField(default=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("GENERATING", "Generating video"),
                            ("READY", "Video ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                (
                    "final_video",
                    models.FileField(
                        blank=True, null=True, upload_to="generated/videos/"
                    ),
                ),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_scripts",
                        to="products.product",
                    ),
                ),
                (
                    "source_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ai.airequest",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_scripts",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoScene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("duration", models.PositiveIntegerField(default=5)),
                ("visual_prompt", models.TextField()),
                ("motion_prompt", models.TextField(blank=True)),
                ("narration", models.TextField(blank=True)),
                (
                    "transition",
                    models.CharField(
                        choices=[
                            ("CONTINUE", "Continue from last frame"),
                            ("TRANSITION", "Soft transition"),
                            ("NEW_SCENE", "New visual anchor"),
                        ],
                        default="CONTINUE",
                        max_length=12,
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenes",
                        to="content.videoscript",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("script", "index"), name="uniq_scene_index"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VideoSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("index", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("GENERATING", "Generating"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("anchor_source", models.CharField(blank=True, max_length=200)),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="generated/videos/"
                    ),
                ),
                (
                    "last_frame",
                    models.FileField(
                        blank=True, null=True, upload_to="generated/frames/"
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="content.videoscript",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("script", "index"), name="uniq_segment_index"
                    )
                ],
            },
        ),
    ]
