# Generated by Django 5.2.10 on 2026-08-27 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_marketresearch"),
        ("content", "0001_initial"),
        ("products", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoscript",
            name="final_video_voiced",
            field=models.FileField(
                blank=True, null=True, upload_to="generated/videos/"
            ),
        ),
        migrations.AddField(
            model_name="videoscript",
            name="voice_audio",
            field=models.FileField(blank=True, null=True, upload_to="generated/audio/"),
        ),
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("POSTER", "Advertising poster"),
                            ("PRODUCT_SHOT", "Instagram-ready product photo"),
                            ("ENHANCED", "Product-preserving enhancement"),
                        ],
                        max_length=16,
                    ),
                ),
                ("concept", models.TextField(blank=True)),
                ("prompt_en", models.TextField(blank=True)),
                ("negative_en", models.TextField(blank=True)),
                ("style", models.CharField(blank=True, max_length=200)),
                ("instructions", models.TextField(blank=True)),
                ("image", models.FileField(upload_to="generated/images/")),
                ("workflow_version", models.CharField(blank=True, max_length=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_images",
                        to="products.product",
                    ),
                ),
                (
                    "source_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="products.productimage",
                    ),
                ),
                (
                    "source_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ai.airequest",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_images",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
