# Generated by Django 5.2.10 on 2026-08-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_videoscript_final_video_voiced_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoscript",
            name="narration_language",
            field=models.CharField(default="fa", max_length=5),
        ),
    ]
