# Generated by Django 5.2.10 on 2026-08-29 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_videoscript_narration_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="caption",
            name="about_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captions",
                to="content.generatedimage",
            ),
        ),
        migrations.AddField(
            model_name="caption",
            name="about_video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captions",
                to="content.videoscript",
            ),
        ),
    ]
