# Generated by Django 5.2.10 on 2026-09-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_caption_about_image_caption_about_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoscene",
            name="state",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="videosegment",
            name="scene_state",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
