/**
 * Home page wording.
 *
 * Beside the page rather than in `dict.ts` because none of it is reused. The
 * shared vocabulary (nav, buttons) stays global; a hero headline does not.
 */
export const HOME = {
  fa: {
    heroTitle: "بازاریابی فروشگاه شما،",
    heroTitleAccent: "خودکار",
    heroLead:
      "پوستر، ویدیوی پیوسته و کپشن — همه از یک ورودی، همه هماهنگ با هم.",
    // "چند دقیقه" was a promise our own render figures contradict: captions are
    // minutes, a rendered video is not. This says what is true for both.
    heroBadge: "از عکس واقعی محصول",
    seeWorkMore: "نمونه‌کارهای بیشتر",
    seeWorkMoreArrow: "نمونه‌کارهای بیشتر ←",
    oneProduct: "یک محصول، سه خروجی",
    outHeads: { poster: "🎨 پوستر", video: "🎬 ویدیو", caption: "✍️ کپشن", agent: "🤝 پشتیبان فروش" },
    posterAlt: (product: string) => `پوستر تولیدشده برای ${product}`,
    posterAltFull: "پوستر تبلیغاتی تولیدشده با آپ‌مارکت برای یک کت اورسایز کرم",
    segment: (n: string) => `قطعه ${n}`,
    fromOnePhoto: (n: string) => `از یک عکس، ${n} قطعه‌ی پیوسته`,

    problemEyebrow: "مشکل",
    problemTitle: "برای یک صفحه‌ی حرفه‌ای، به چند نفر نیاز دارید",
    problemLead: "و هرکدام باید استخدام، هماهنگ و پرداخت شوند.",

    solutionEyebrow: "راه‌حل",
    solutionTitle: "یک پلتفرم به‌جای یک تیم",
    solutionLead: "همه‌ی مسیر، از ثبت محصول تا انتشار و پاسخ به مشتری.",

    audienceEyebrow: "برای چه کسب‌وکارهایی",
    audienceTitle: "هر فروشگاهی که محصول فیزیکی می‌فروشد",
    audienceLead: "سه دسته‌ی اول نمونه‌ی واقعی دارند؛ بقیه همان شکل از مسئله‌اند.",
    proven: "✓ نمونه دارد",

    processEyebrow: "فرایند",
    processTitle: "چطور کار می‌کند",
    processLead: "شش قدم، یک‌بار تنظیم.",
    step: "قدم",

    vsEyebrow: "در برابر",
    vsTitle: "در برابر تیم داخلی",

    objectionsEyebrow: "نگرانی‌های رایج",
    objectionsTitle: "آنچه معمولاً می‌پرسند",

    trustEyebrow: "خیال راحت",
    trustTitle: "بدون ریسک شروع کنید",

    savingLabel: "تومان صرفه‌جویی در ماه",
    firstOutputValue: "همان جلسه",
    firstOutputLabel: "تا اولین خروجی",
    firstOutputNote: "کپشن در چند دقیقه؛ ویدیو در صف رندر",

    ctaTitle: "همین امروز شروع کنید",
    ctaLead:
      "فروشگاه و چند محصولتان را ثبت کنید و اولین بسته‌ی محتوا را در همین جلسه تحویل بگیرید.",
    ctaNote: "دو هفته رایگان، بدون کارت بانکی",
    seePricing: "دیدن قیمت‌ها",
  },

  en: {
    heroTitle: "Your shop's marketing,",
    heroTitleAccent: "on autopilot",
    heroLead:
      "Poster, continuous video and caption — one input, all of it consistent.",
    heroBadge: "From your real product photo",
    seeWorkMore: "More samples",
    seeWorkMoreArrow: "More samples →",
    oneProduct: "One product, three outputs",
    outHeads: { poster: "🎨 Poster", video: "🎬 Video", caption: "✍️ Caption", agent: "🤝 Sales assistant" },
    posterAlt: (product: string) => `Poster generated for ${product}`,
    posterAltFull: "An advertising poster generated by UpMarket for a cream oversized coat",
    segment: (n: string) => `Segment ${n}`,
    fromOnePhoto: (n: string) => `${n} continuous segments from one photo`,

    problemEyebrow: "The problem",
    problemTitle: "A professional page takes a whole team",
    problemLead: "And every one of them has to be hired, coordinated and paid.",

    solutionEyebrow: "The answer",
    solutionTitle: "One platform instead of a team",
    solutionLead: "The whole path, from adding a product to publishing it and answering buyers.",

    audienceEyebrow: "Who it is for",
    audienceTitle: "Any shop selling a physical product",
    audienceLead: "The first three have real samples; the rest are the same shape of problem.",
    proven: "✓ Sample available",

    processEyebrow: "The process",
    processTitle: "How it works",
    processLead: "Six steps, set up once.",
    step: "Step",

    vsEyebrow: "Compared",
    vsTitle: "Against an in-house team",

    objectionsEyebrow: "Common doubts",
    objectionsTitle: "What people usually ask",

    trustEyebrow: "Peace of mind",
    trustTitle: "Start without risk",

    savingLabel: "toman saved per month",
    firstOutputValue: "Same sitting",
    firstOutputLabel: "to your first output",
    firstOutputNote: "Captions in minutes; video in the render queue",

    ctaTitle: "Start today",
    ctaLead:
      "Add your shop and a few products, and take your first content pack away in this sitting.",
    ctaNote: "Two weeks free, no card required",
    seePricing: "See pricing",
  },
} as const;
