# Generated by Django 5.2.10 on 2026-08-27 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("product_analysis", "Product analysis"),
                            ("image_generation", "Image generation"),
                            ("video_script_generation", "Video script generation"),
                            ("video_segment_generation", "Video segment generation"),
                            ("video_concatenation", "Video concatenation"),
                            ("voice_generation", "Voice generation"),
                            ("publishing", "Publishing"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("progress_step", models.PositiveIntegerField(default=0)),
                ("total_steps", models.PositiveIntegerField(default=0)),
                ("current_step_label", models.CharField(blank=True, max_length=200)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("celery_task_id", models.CharField(blank=True, max_length=64)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["state"], name="jobs_job_state_7f24c5_idx"),
                    models.Index(
                        fields=["store", "created_at"],
                        name="jobs_job_store_i_38eccf_idx",
                    ),
                ],
            },
        ),
    ]
