# Generated by Django 5.2.10 on 2026-08-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_alter_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.CharField(
                choices=[
                    ("product_analysis", "Product analysis"),
                    ("market_analysis", "Market / competitor analysis"),
                    ("caption_generation", "Caption generation"),
                    ("image_generation", "Image generation"),
                    ("video_generation", "Video generation"),
                    ("video_script_generation", "Video script generation"),
                    ("video_segment_generation", "Video segment generation"),
                    ("video_concatenation", "Video concatenation"),
                    ("voice_generation", "Voice generation"),
                    ("publishing", "Publishing"),
                    ("embedding_build", "Product embeddings build"),
                ],
                max_length=40,
            ),
        ),
    ]
