# Generated by Django 5.2.10 on 2026-09-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_job_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="cancel_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="mode",
            field=models.CharField(
                choices=[
                    ("SAFE", "محافظه\u200cکارانه — هر قطعه را تأیید کن"),
                    ("AUTO", "خودکار — فقط زیر آستانه\u200cی کیفیت بایست"),
                ],
                default="SAFE",
                max_length=6,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="preview",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="job",
            name="state",
            field=models.CharField(
                choices=[
                    ("QUEUED", "در صف"),
                    ("PROCESSING", "در حال پردازش"),
                    ("PREVIEW", "پیش\u200cنمایش آماده"),
                    ("WAITING_APPROVAL", "منتظر تأیید"),
                    ("APPROVED", "تأیید شد"),
                    ("RENDERING", "در حال رندر نهایی"),
                    ("QC", "بررسی کیفیت"),
                    ("COMPLETED", "تمام شد"),
                    ("FAILED", "شکست خورد"),
                    ("CANCELLED", "لغو شد"),
                    ("RUNNING", "در حال اجرا (قدیمی)"),
                ],
                default="QUEUED",
                max_length=16,
            ),
        ),
    ]
