# Generated by Django 5.2.10 on 2026-09-12 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_job_cancel_requested_job_mode_job_preview_and_more"),
        ("stores", "0004_salesagentsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="RenderMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("VIDEO_SEGMENT", "قطعه ویدیو"),
                            ("IMAGE", "تصویر"),
                            ("TEXT", "متن / تحلیل"),
                            ("VISION", "تحلیل تصویر"),
                            ("MODEL_SWAP", "جابه\u200cجایی مدل روی کارت"),
                            ("AUDIO", "صداگذاری"),
                        ],
                        max_length=16,
                    ),
                ),
                ("engine", models.CharField(max_length=120)),
                ("hardware", models.CharField(max_length=120)),
                ("duration_s", models.FloatField()),
                ("output_units", models.FloatField(default=1)),
                ("resolution", models.CharField(blank=True, max_length=20)),
                ("vram_peak_mb", models.PositiveIntegerField(blank=True, null=True)),
                ("load_s", models.FloatField(blank=True, null=True)),
                ("succeeded", models.BooleanField(default=True)),
                ("error_kind", models.CharField(blank=True, max_length=80)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metrics",
                        to="jobs.job",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="render_metrics",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "اندازه\u200cگیری رندر",
                "verbose_name_plural": "اندازه\u200cگیری\u200cهای رندر",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["kind", "engine", "hardware"],
                        name="jobs_render_kind_4570bf_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="jobs_render_created_690abb_idx"
                    ),
                ],
            },
        ),
    ]
