# Generated by Django 5.2.10 on 2026-08-27 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
        ("products", "0001_initial"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("REASONING", "Reasoning"),
                            ("VISION", "Vision"),
                            ("CODE", "Code"),
                        ],
                        max_length=16,
                    ),
                ),
                ("model", models.CharField(max_length=64)),
                ("prompt_id", models.CharField(max_length=64)),
                ("prompt_version", models.CharField(max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OK", "OK"),
                            ("TIMEOUT", "Timeout"),
                            ("PROVIDER_ERROR", "Provider error"),
                            ("MALFORMED_OUTPUT", "Malformed output"),
                            ("VALIDATION_FAILED", "Validation failed"),
                        ],
                        default="OK",
                        max_length=24,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_requests",
                        to="jobs.job",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_requests",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_output", models.TextField(blank=True)),
                ("parsed", models.JSONField(blank=True, null=True)),
                ("valid", models.BooleanField(default=False)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="ai.airequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductIntelligence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("summary", models.TextField(blank=True)),
                ("target_audience", models.JSONField(blank=True, default=list)),
                ("selling_points", models.JSONField(blank=True, default=list)),
                ("weaknesses", models.JSONField(blank=True, default=list)),
                ("objections", models.JSONField(blank=True, default=list)),
                ("marketing_angles", models.JSONField(blank=True, default=list)),
                ("recommended_tone", models.CharField(blank=True, max_length=100)),
                ("content_ideas", models.JSONField(blank=True, default=list)),
                ("use_cases", models.JSONField(blank=True, default=list)),
                ("visual_analysis", models.JSONField(blank=True, default=list)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligence",
                        to="products.product",
                    ),
                ),
                (
                    "source_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ai.airequest",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "product intelligence",
            },
        ),
    ]
