# Generated by Django 5.2.10 on 2026-08-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productintelligence",
            name="positioning",
            field=models.TextField(blank=True),
        ),
    ]
