# Generated by Django 5.2.10 on 2026-09-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0005_productembedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("TEXT", "متن، تحلیل و ریسرچ"),
                            ("VISION", "تحلیل تصویر"),
                            ("IMAGE", "تولید تصویر"),
                            ("VIDEO", "تولید ویدیو"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("OLLAMA", "Ollama (لوکال)"),
                            ("COMFYUI", "ComfyUI (لوکال)"),
                            ("OPENAI", "OpenAI-compatible API"),
                            ("REPLICATE", "Replicate"),
                            ("HTTP", "HTTP سفارشی"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="نام دلخواه برای تشخیص در پنل", max_length=80
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="مثال: http://127.0.0.1:11434 یا https://api.openai.com/v1 — خالی یعنی از مقدار .env استفاده شود",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="برای سرویس\u200cهای لوکال خالی بگذار",
                        max_length=255,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="نام مدل یا ورک\u200cفلو. مثال: qwq:32b · gpt-4o-mini · wan22_i2v@v1",
                        max_length=120,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=100, help_text="کمتر = زودتر امتحان می\u200cشود"
                    ),
                ),
                ("timeout_s", models.PositiveIntegerField(default=600)),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="پارامترهای اضافه به\u200cصورت JSON (temperature، steps، …)",
                    ),
                ),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("is_healthy", models.BooleanField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "AI provider",
                "ordering": ["capability", "priority", "id"],
                "indexes": [
                    models.Index(
                        fields=["capability", "is_active", "priority"],
                        name="ai_modelpro_capabil_2815b2_idx",
                    )
                ],
            },
        ),
    ]
