# Generated by Django 5.2.10 on 2026-09-12 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0006_modelprovider"),
        ("stores", "0002_storeprofile_novinhub_account_ids_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="modelprovider",
            name="allowed_data",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="خالی برای سرویس لوکال یعنی همه\u200cچیز؛ برای سرویس بیرونی یعنی فقط محصول و برند.",
                verbose_name="مجاز برای کدام داده",
            ),
        ),
        migrations.AddField(
            model_name="modelprovider",
            name="data_location",
            field=models.CharField(
                choices=[
                    ("ON_PREMISE", "روی سرور خودمان"),
                    ("IRAN", "ایران"),
                    ("EU", "اتحادیه اروپا"),
                    ("US", "آمریکا"),
                    ("OTHER", "جای دیگر"),
                    ("UNKNOWN", "نامشخص"),
                ],
                default="UNKNOWN",
                max_length=12,
                verbose_name="داده کجا پردازش می\u200cشود",
            ),
        ),
        migrations.AddField(
            model_name="modelprovider",
            name="data_retention",
            field=models.CharField(
                blank=True,
                help_text="مثال: «۳۰ روز برای پایش سوءاستفاده» یا «نگه\u200cداری نمی\u200cشود».",
                max_length=200,
                verbose_name="نگه\u200cداری داده",
            ),
        ),
        migrations.AddField(
            model_name="modelprovider",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="فروشگاه\u200cهایی که «فقط سرویس\u200cهای تأییدشده» را انتخاب کرده\u200cاند، تنها از سرویس\u200cهای تیک\u200cخورده استفاده می\u200cکنند.",
                verbose_name="تأییدشده",
            ),
        ),
        migrations.AddField(
            model_name="modelprovider",
            name="privacy_policy_url",
            field=models.URLField(blank=True, verbose_name="لینک سیاست حریم خصوصی"),
        ),
        migrations.CreateModel(
            name="StoreAIPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            (
                                "LOCAL_ONLY",
                                "فقط لوکال — هیچ داده\u200cای از سرور خارج نمی\u200cشود",
                            ),
                            ("APPROVED_EXTERNAL", "فقط سرویس\u200cهای تأییدشده"),
                            ("HYBRID", "ترکیبی — هر سرویس فعالی، با اعلام شفاف"),
                        ],
                        default="HYBRID",
                        max_length=20,
                    ),
                ),
                (
                    "allow_customer_data_external",
                    models.BooleanField(
                        default=False,
                        help_text="پیش\u200cفرض خاموش. پیام خصوصی مشتری، داده\u200cی خود اوست نه فروشگاه.",
                        verbose_name="ارسال پیام\u200cهای مشتری به سرویس بیرونی",
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_policy",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI data policy",
                "verbose_name_plural": "AI data policies",
            },
        ),
    ]
